pool:
  vmImage: windows-latest

variables:
  solution: './ClientLibrary/Samples/ClientSamples.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET 8.0.x SDK
  inputs:
    version: 8.0.x

- task: NuGetAuthenticate@1
  displayName: Authenticate with Azure Artifacts

- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: "restore"
    projects: "**/*.csproj"
    feedsToUse: "select"
    #vstsFeed: "8ac2e5c3-c800-4154-858f-5970c6d39629/86717379-19c1-4da3-8909-51d796a63034"
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  inputs:
    command: "build"
    projects: "**/*.csproj"
    configuration: "Release"
    displayName: "Build Function project"
    
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

